version: '3.1'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE}
